name: Stable lints

# We only run these lints on trial-merges of PRs to reduce noise.
on: pull_request

jobs:
  clippy:
    name: Clippy (1.56.1)
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: rust
        run: echo "toolchain=$(cat rust-toolchain)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.rust.outputs.toolchain }}
      - name: Run clippy
        run: cargo clippy --all-features --all-targets -- -D warnings
        shell: bash
